name: Build
on:
  workflow_call:
    secrets:
      TAURI_SIGNING_PRIVATE_KEY:
        required: true
      TAURI_SIGNING_PRIVATE_KEY_PASSWORD:
        required: true

jobs:
  build:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: ubuntu-latest
            target: ""
            args: ""
            shell: bash
          - platform: macos-latest # for Arm based macs (M1 and above).
            target: "aarch64-apple-darwin"
            args: ""
            shell: bash
          - platform: macos-latest # for Intel based macs.
            target: "x86_64-apple-darwin"
            args: ""
            shell: bash
          - platform: windows-latest
            target: "aarch64-pc-windows-msvc"
            args: "--bundles nsis"
            shell: pwsh
          - platform: windows-latest
            target: "x86_64-pc-windows-msvc"
            args: ""
            shell: pwsh
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/setup
        with:
          ubuntu-dependencies: true

      - name: Build Frontend
        run: bun run build:frontend

      - name: Build Tauri
        uses: tauri-apps/tauri-action@v0
        env:
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tauriScript: "bun x tauri"
          args: ${{ matrix.target && format('--target {0}', matrix.target) }} ${{ matrix.args }}
