name: delete
on:
  workflow_dispatch:

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - name: Clean Up
        id: release
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
              const { owner, repo } = context.repo;
              const { workflow_runs: runs } = await github.rest.request('GET /repos/{owner}/{repo}/actions/runs', {
                owner,
                repo,
                headers: {
                  'X-GitHub-Api-Version': '2022-11-28'
                }
              })

              for (const { id } of runs) {
                await github.rest.request('GET /repos/{owner}/{repo}/actions/runs', {
                  owner,
                  repo,
                  headers: {
                    'X-GitHub-Api-Version': '2022-11-28'
                  }
                }).catch(() => {
                  console.log(`Error: Unable to delete ${id}`);
                })

                await new Promise(r => setTimeout(r, 500));
              }