name: delete
on:
  workflow_dispatch:

jobs:
  delete:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Clean Up
        id: clean
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
              const { owner, repo } = context.repo;
              const { data: { workflow_runs: runs } } = await github.request('GET /repos/{owner}/{repo}/actions/runs', {
                owner,
                repo,
                headers: {
                  'X-GitHub-Api-Version': '2022-11-28'
                }
              })

              for (const { id: run_id } of runs) {
                await github.request('DELETE /repos/{owner}/{repo}/actions/runs/{run_id}', {
                  owner,
                  repo,
                  run_id,
                  headers: {
                    'X-GitHub-Api-Version': '2022-11-28'
                  }
                }).then(() => {
                  console.log(`Deleted run ${run_id}`);
                }).catch((e) => {
                  console.log(`Error: Unable to delete ${run_id}\n${e}`);
                })

                await new Promise(r => setTimeout(r, 500));
              }