name: Publish
on:
  release:
    types: 
      - published

jobs:
  desktop:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: ubuntu-latest
            target: ""
            args: ""
            shell: bash
          - platform: macos-latest # for Arm based macs (M1 and above).
            target: "aarch64-apple-darwin"
            args: ""
            shell: bash
          - platform: macos-latest # for Intel based macs.
            target: "x86_64-apple-darwin"
            args: ""
            shell: bash
          - platform: windows-latest
            target: "aarch64-pc-windows-msvc"
            args: "--bundles nsis"
            shell: pwsh
          - platform: windows-latest
            target: "x86_64-pc-windows-msvc"
            args: ""
            shell: pwsh
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/setup
        with:
          ubuntu-dependencies: true

      - name: Build & Publish
        uses: tauri-apps/tauri-action@v0
        env:
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRERELEASE: ${{ github.ref_name != 'main' }}
        with:
          tauriScript: "bun x tauri"
          releaseId: ${{ needs.release.outputs.RELEASE_UPLOAD_ID }}

  android:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: ubuntu-latest
            shell: bash
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/setup
        with:
          android: true

      - name: Build & Publish
        uses: tauri-apps/tauri-action@v0
        env:
          NDK_HOME: ${{ steps.ndk.outputs.ndk-path }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRERELEASE: ${{ github.ref_name != 'main' }}
        with:
          tauriScript: "bun x tauri android build"
          args: ${{ matrix.target && format('--target {0}', matrix.target) }} ${{ matrix.args }}
          releaseId: ${{ needs.release.outputs.RELEASE_UPLOAD_ID }}
        