name: release
on:
  pull_request:
    types:
      - closed
    branches:
      - main
      - next
  workflow_dispatch:
  workflow_call:

jobs:
  # test:
  #   permissions:
  #     contents: write
  #   uses: ./.github/workflows/test.yml
  #   secrets: inherit
  
  release:
    # needs: test
    permissions:
      contents: write # to create release (changesets/action)
      pull-requests: write # to create pull request (changesets/action)
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: ubuntu-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Build
        uses: ./.github/setup

      # - name: Next Version
      #   run: |
      #     echo "VERSION=$(bun x changeset status --output=release.json && jq -r '.releases[0].newVersion' release.json && rm release.json)" >> "$GITHUB_ENV"

      - name: Create Release
        id: changesets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: changesets/action@v1
        with:
          # commit: "chore(release): v${{ env.VERSION }}"
          # title: "release v${{ env.VERSION }}"
          version: bun x changeset version
          publish: bun x changeset publish

      - name: Release Id 
        id: release
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const releases = ${{ steps.changesets.outputs.publishedPackages }};

            for (const { name, version: tag } of releases) {
              const [owner, repo] = name.split('/');

              const { id } = await github.rest.repos.getReleaseByTag({
                owner,
                repo,
                tag
              });

              core.setOutput('id', id);
            }

  desktop:
    needs: release
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: ubuntu-latest
            target: ""
            args: ""
            shell: bash
          - platform: macos-latest # for Arm based macs (M1 and above).
            target: "aarch64-apple-darwin"
            args: ""
            shell: bash
          - platform: macos-latest # for Intel based macs.
            target: "x86_64-apple-darwin"
            args: ""
            shell: bash
          - platform: windows-latest
            target: "aarch64-pc-windows-msvc"
            args: "--bundles nsis"
            shell: pwsh
          - platform: windows-latest
            target: "x86_64-pc-windows-msvc"
            args: ""
            shell: pwsh
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/setup
        with:
          ubuntu-dependencies: true

      - name: Build & Publish
        uses: tauri-apps/tauri-action@v0
        env:
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRERELEASE: ${{ github.ref_name != 'main' }}
        with:
          tauriScript: "bun x tauri"
          args: ${{ matrix.target && format('--target {0}', matrix.target) }} ${{ matrix.args }}
          releaseId: ${{ steps.release.outputs.id }}

  android:
    needs: release
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: ubuntu-latest
            target: aarch64-linux-android
            args: ""
            shell: bash
          - platform: ubuntu-latest
            target: x86_64-linux-android
            args: ""
            shell: bash
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup
        id: setup
        uses: ./.github/setup
        with:
          android: true

      - name: Build & Publish
        uses: tauri-apps/tauri-action@v0
        env:
          NDK_HOME: ${{ steps.setup.outputs.ndk-path }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRERELEASE: ${{ github.ref_name != 'main' }}
        with:
          tauriScript: "bun x tauri android"
          args: ${{ matrix.target && format('--target {0}', matrix.target) }} ${{ matrix.args }}
          releaseId: ${{ steps.release.outputs.id }}
        